## Практическое задание к 3-му уроку

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$



In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
import matplotlib.pyplot as plt

In [2]:
def calc_eig(A):
    w, v = np.linalg.eig(A)
    print(f'Матрица A:\n{A}')
    print(f'Собственные значения оператора:\n{w}')
    print(f'Собственные векторы оператора:\n{v}')

In [3]:
A = np.array([[-1, -6], [2, 6]])
calc_eig(A)

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения оператора:
[2. 3.]
Собственные векторы оператора:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.



#### Ответ:

$$-1\begin{pmatrix}
1 & 0\\ 
0 & 1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$
$$\lambda=-1$$
Здесь видно, что любой вектор является собственным

In [4]:
A = np.array([[1, 0], [0, -1]])

print(A * A.T, "Матрица ортогональная")

calc_eig(A)


[[1 0]
 [0 1]] Матрица ортогональная
Матрица A:
[[ 1  0]
 [ 0 -1]]
Собственные значения оператора:
[ 1. -1.]
Собственные векторы оператора:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



#### Ответ:

$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$
Вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного исходной матрицей.

In [5]:
A = np.array([[1, 1], [-1, 3]])
calc_eig(A)

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения оператора:
[2. 2.]
Собственные векторы оператора:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

#### Ответ:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}
$$
$$\begin{cases}
9=3\cdot\lambda \\ 
-9=-3\cdot\lambda \\ 
-12=-4\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=3\\ 
\lambda=3\\ 
\lambda=3
\end{cases}.$$
Вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [6]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
calc_eig(A)

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения оператора:
[ 3. -3.  3.]
Собственные векторы оператора:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]
