### Практическое задание ко второму уроку

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


__Ответ:__

   а) Матрицы не перемножаются, количество строк первого не равно количеству столбцов второго;
    
   б) Можно перемножить только $B$ на $A$, размерность 3х2 ;
    
   в) Определены оба произведения, размерность 8х8, при обратном 3х3 ;
    
   г) Определены оба произведения, размерность 4х4 в обоих случаях .

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 0], [2, 1], [10, 5], [10, 5]])
B = np.array([[1, 0], [2, 1], [10, 5], [10, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1  0]
 [ 2  1]
 [10  5]
 [10  5]]
Матрица B
[[ 1  0]
 [ 2  1]
 [10  5]
 [10  5]]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [3]:
A = np.array([[1, 0], [2, 1], [10, 3], [10, 5], [13, 2]])
B = np.array([[2, 4, 1, 1, 9], [2, 5, 3, 1, 9], [2, 7, 4, 8, 9]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1  0]
 [ 2  1]
 [10  3]
 [10  5]
 [13  2]]
Матрица B
[[2 4 1 1 9]
 [2 5 3 1 9]
 [2 7 4 8 9]]
Матрица BA
[[147  30]
 [169  37]
 [253  77]]


In [4]:
A = np.array([[1, 0, 3], [2, 1, 5], [10, 3, 7], [10, 5, 8], [13, 2, 31], [17, 2, 3], [3, 5, 31], [13, 7, 1]])
B = np.array([[2, 4, 1, 1, 9, 2, 1, 5], [2, 5, 3, 1, 9, 10, 3, 7], [2, 7, 4, 8, 9, 13, 2, 31]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1  0  3]
 [ 2  1  5]
 [10  3  7]
 [10  5  8]
 [13  2 31]
 [17  2  3]
 [ 3  5 31]
 [13  7  1]]
Матрица B
[[ 2  4  1  1  9  2  1  5]
 [ 2  5  3  1  9 10  3  7]
 [ 2  7  4  8  9 13  2 31]]
Матрица AB
[[   8   25   13   25   36   41    7   98]
 [  16   48   25   43   72   79   15  172]
 [  40  104   47   69  180  141   33  288]
 [  46  121   57   79  207  174   41  333]
 [  92  279  143  263  414  449   81 1040]
 [  44   99   35   43  198   93   29  192]
 [  78  254  142  256  351  459   80 1011]
 [  42   94   38   28  189  109   36  145]]
Матрица BA
[[249  74 362]
 [439 121 469]
 [883 330 544]]


In [5]:
A = np.array([[9, 4, 5, 1], [2, 3, 8, 4], [2, 5, 6, 8], [5, 2, 1, 4]])
B = np.array([[2, 4, 1, 1], [2, 5, 3, 1], [2, 7, 4, 8], [9, 2, 1, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[9 4 5 1]
 [2 3 8 4]
 [2 5 6 8]
 [5 2 1 4]]
Матрица B
[[2 4 1 1]
 [2 5 3 1]
 [2 7 4 8]
 [9 2 1 5]]
Матрица AB
[[45 93 42 58]
 [62 87 47 89]
 [98 91 49 95]
 [52 45 19 35]]
Матрица BA
[[ 33  27  49  30]
 [ 39  40  69  50]
 [ 80  65  98  94]
 [112  57  72  45]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Ответ:__
$$\begin{pmatrix}
1 + 4 & -2 -1 \\ 
3 + 0 & 0 + 5 \\  
\end{pmatrix}=\begin{pmatrix}
5 & -3 \\ 
3 &  5 \\  
\end{pmatrix}$$

$$A\cdot B=\begin{pmatrix}
1\cdot4+(-2)\cdot0 & 1\cdot(-1)+(-2)\cdot5 \\
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5 \\ 
\end{pmatrix}=\begin{pmatrix}
4 & -11 \\ 
12 & -3 \\ 
\end{pmatrix}.$$

In [6]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [14]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A\n{A}')
print(f'Матрица AT\n{A.T}')
print(f'Матрица A*AT\n{np.dot(A, A.T)}')
print(f'Матрица AT*A\n{np.dot(A.T, A)}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица AT
[[ 4  5  2]
 [ 1 -2  3]]
Матрица A*AT
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица AT*A
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [8]:
def dot_matrix(A, B):
    rowA, columnA = A.shape[0], A.shape[1]
    rowB, columnB = B.shape[0], B.shape[1]
    if columnA != rowB:
        print(f'Матрицы не перемножаются')
    else:
        Matrix = [[0 for x in range(columnB)] for y in range(rowA)]
        print(Matrix)
        for i in range(rowA):
            for j in range(columnB):
                counter = 0
                while counter < columnA:
                    Matrix[i][j] += A[i][counter] * B[counter][j]
                    counter += 1
    return Matrix

In [9]:
A = np.array([[1, -2], [3, 0], [9, 5]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица AB\n{np.dot(A, B)}')

print(dot_matrix(A, B))

print(A[1][1])
print(A)

Матрица AB
[[  4 -11]
 [ 12  -3]
 [ 36  16]]
[[0, 0], [0, 0], [0, 0]]
[[4, -11], [12, -3], [36, 16]]
0
[[ 1 -2]
 [ 3  0]
 [ 9  5]]


In [10]:
A.shape[1]

2

#### Практические задания из Методички 4

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Ответ 1__

а)
$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}$$ = $$sin^{2}x -(-cos^{2}x)$$ = 1

б)
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$ = $$

In [20]:
B = np.matrix('4, 2, 3; 0, 5, 1; 0, 0, 9')
np.linalg.det(B)

180.0